from planscore.upload_fields import lambda_handler as upload_fields
from planscore.preread import lambda_handler as preread
from planscore.preread_followup import lambda_handler as preread_followup
from planscore.postread_callback import lambda_handler as postread_callback
from planscore.postread_calculate import lambda_handler as postread_calculate
from planscore.run_tile import lambda_handler as run_tile
from planscore.run_slice import lambda_handler as run_slice
from planscore.observe import lambda_handler as observe_tiles
from planscore.authorizer import lambda_handler as authorizer
from planscore.api_upload import lambda_handler as api_upload
from planscore.api_uploaded import lambda_handler as api_uploaded
from planscore.get_states import lambda_handler as get_states
from planscore.polygonize import lambda_handler as polygonize
